on:
  workflow_call:
    inputs:
      package_name:
        required: true
        type: string
jobs:
  publish-npm:
    uses: hkyhy/actions/.github/workflows/publish-npm-workflow.yml@master
    secrets: inherit
    with:
      package_name: ${{inputs.package_name}}
#  release:
#    needs: publish-npm
#    uses: hkyhy/actions/.github/workflows/npm-release-workflow.yml@master
#    secrets: inherit
#    with:
#      package_name: ${{inputs.package_name}}